name: thejourney
favicon: null
layout_spectrum: 0.3616023960057646
typography_spectrum: 0.4113011022564024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#272329'
    - '#5b593b'
    - '#bcbec9'
    - '#95975a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5118671508971602
purpose: []
