name: thejourney
favicon: null
layout_spectrum: 0.3616023960057646
typography_spectrum: 0.4113011022564024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.797760562505573
  lightness: 0.5833312217146158
  saturation: 0.3795011870097369
  rhythmicContrast: 0.5118671508971602
purpose: []
